name: e_commerce_getx
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  auto_animated: ^3.2.0
  badges: ^3.1.2
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dropdown_search: ^5.0.6
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  flutter_polyline_points: ^2.0.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.6.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  get: ^4.6.6
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.2.1
  grouped_list: ^5.1.2
  http: ^1.1.2
  image_picker: ^1.0.5
  image_pickers: ^2.0.4+8
  intl: ^0.18.1
  jiffy: ^6.2.1
  path: ^1.8.3
  qr_flutter: ^4.1.0
  responsive_builder: ^0.7.0
  scan: ^1.6.0
  shared_preferences: ^2.2.2
  show_up_animation: ^2.0.0
  sqflite: ^2.3.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/avatar.png
    - assets/lottie/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
